### ISSUE TITLE
Implement the single Page that redirects to various books

### ISSUE THREAD

**Issue by segullshairbutt** [segullshairbutt/islamopedia-books#3]
### Description
We need to implement a dynamic navigation system for our static HTML pages hosted using GitHub Pages. The navigation should be generated automatically based on the directory structure defined in [Directory structuring guide](./docs/directory-structuring.md). The navigation bar must be responsive, collapsible, and expandable. The approach to generate this navigation is still open to discussion; it can be a pre-commit hook that generates static HTML content or an inline React solution that dynamically creates the navigation.

### Background
This repository contains the markup format of a book, primarily written in HTML. The content is organized in a specific directory structure as detailed in ./docs/directory-structuring.md. Users should be able to navigate through the content using a dynamic navigation bar that reflects this structure. The navigation bar should be easy to use and should not alter the output of the static HTML content.

#### Navigation Generation:
- Automatically generate a navigation structure based on the directory structure.
- Ensure that the navigation includes links to all pages of each book and sub-sections as defined in the directory structure.
#### Navigation Bar Features:
-The navigation bar should be responsive, ensuring usability on different devices (desktops, tablets, and mobile phones).
- It should be collapsible and expandable to allow users to hide or show different sections as needed.
#### Implementation Options:
- Pre-commit Hook: A script that generates the navigation structure as static HTML content before each commit.
- Inline React: An inline React script that dynamically creates the navigation on the client side.

### Acceptance Criteria
- The navigation structure is automatically generated based on the directory structure.
- The navigation bar is responsive, collapsible, and expandable.
- The navigation links work correctly, allowing users to access each page of the book.
- The implementation should not alter the output of the static HTML content.
- If using a pre-commit hook, ensure it runs efficiently and does not significantly delay the commit process.
- If using inline React, ensure it does not impact the loading time or performance of the pages.

**Comment by SyedJamal030** [comment]
Building the Navigation will not be difficult; as you indicated, we must convert our directories into navigation. The first thing that comes to mind is the **Tree View Layout**.
[Checkout this code example](https://www.codehim.com/menu/css-and-jquery-tree-view-navigation-menu-treenav/)

![image](https://github.com/segullshairbutt/islamopedia-books/assets/46771860/e867f937-fcef-4b90-9fb0-fb091be69ffb)

**Comment by segullshairbutt** [comment]
This is not relevent anymore. We are using the jupyter notebooks standard to create the scalable books.
